<!-- Startseite -->
<div class="row">
	<div class="span12">
		<p style="text-align: center;">
			<img src="http://ehcserver.jochen-bauer.net/img/ehome-center-logo.png"
				alt="Bild Header E|Home-Center" />
		</p>
	</div>
</div>
<div class="hero-unit">
    <h1><?php echo sprintf("Willkommen!", '<span class="zf-green">', '</span>') ?></h1>
    <p>
    	Mustermann, Musterweg 13, 12345 Musterstadt
    </p>
    <p>
    	<a class="btn btn-warning btn-large" href="<?php echo $this->url('login') ?>">Eintreten &raquo;</a>
    </p>
</div>