<?php
/**
 * View corresponds to IndexController.loginAction().
 */
?>
	  <!--Top Section-->
      <div class="grid_2 topSection">&nbsp;</div>
      <div class="grid_8 topSection">
        <div>
      		<!-- Widget, header -->
      		<h1 style="text-align: center; color: orange;"><?php echo $widgetHeader; ?></h1>
      		<?php 
      			// Anzeige des Formulars, Verarbeitung in Controller-Action
      			if ($this->message == ""){
      				$this->form->prepare();
      				echo $this->form()->openTag($this->form);
      				echo "<p>Name: <br />";
      				echo $this->formRow($this->form->get('name'));
      				echo "</p>";
      				echo "<p>Passwort: <br />";
      				echo $this->formRow($this->form->get('pass'));
      				echo "</p>";
      				echo "<p>";
      				echo $this->formRow($this->form->get('submit'));
      				echo "</p>";
      				echo $this->form()->closeTag();
      			} else {
					echo $this->message;
					$this->form->prepare();
					echo $this->form()->openTag($this->form);
					echo "<p>";
					echo $this->formRow($this->form->get('submit'));
					echo "</p>";
					echo $this->form()->closeTag();
				}
      		?>
      	</div>
      </div>
      <div class="grid_2 topSection">&nbsp;</div>
      <div class="clear">&nbsp;</div>
      <!--End TopSection-->

      <!--Spacer-->
      <div class="grid_12 spacer"></div>
      <div class="clear">&nbsp;</div>
      <!--End Spacer-->